"""empty message

Revision ID: 60b51d4b33a8
Revises: 6ce3245f809e
Create Date: 2019-08-12 16:28:01.178146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b51d4b33a8'
down_revision = '6ce3245f809e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
