version: "3"

volumes:
  test_app.mq:
    external: true

services:
  rabbitmq:
    container_name: test_app.mq
    image: rabbitmq:latest
    command: rabbitmq-server
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - test_app.mq:/var/lib/rabbitmq/data


