version: "3"

volumes:
  test_app.db:
    external: true

services:
  database:
    container_name: test_app.db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - test_app.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
